field.storage_settings.customfield_custom:
  type: mapping
  label: Custom storage settings
  mapping:
    foo:
      type: string
      label: Foo

field.value.customfield_custom:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value

field.widget.settings.customfield_custom:
  type: mapping
  label: Custom widget settings
  mapping:
    foo:
      type: string
      label: Foo

field.formatter.settings.customfield_custom:
  type: mapping
  label: Custom formatter settings
  mapping:
    foo:
      type: string
      label: Foo
