# Schema for the configuration files of the Database api module.
database_api.settings:
  type: config_object
  label: 'Database api settings'
  mapping:
    term:
      type: string
      label: 'Term'
