config_form.simple_form:
  path: '/customgenericform'
  defaults:
    _form: '\Drupal\config_form\Form\SimpleForm'
    _title: 'Simple Form'
  requirements:
    _permission: view_form_permission

config_form.settings:
  path: '/admin/config/customconfigform'
  defaults:
    _form: '\Drupal\config_form\Form\ConfigForm'
    _title: 'Config Form'
  requirements:
    _permission: view_form_permission
