colorfield.rgb_color_item:
  type: config_object
  label: 'RGB Color Field Item'
  mapping:
    hex_code:
      type: string
      label: 'Hex Code'
    red:
      type: integer
      label: 'Red'
    green:
      type: integer
      label: 'Green'
    blue:
      type: integer
      label: 'Blue'
