field.widget.settings.rgb_color_hex:
  type: mapping
  label: RGB Color Hex widget settings
  mapping:
    foo:
      type: string
      label: Foo

field.widget.settings.rgb_color_component:
  type: mapping
  label: RGB Color Component widget settings
  mapping:
    foo:
      type: string
      label: Foo

field.widget.settings.rgb_color_picker:
  type: mapping
  label: RGB Color Picker widget settings
  mapping:
    foo:
      type: string
      label: Foo

field.formatter.settings.rgb_color_static_text:
  type: mapping
  label: RGB Color Static Text formatter settings
  mapping:
    foo:
      type: string
      label: Foo

field.formatter.settings.rgb_color_static_background:
  type: mapping
  label: RGB Color Static Background formatter settings
  mapping:
    foo:
      type: string
      label: Foo
