form.simpleForm:
  path: '/Customgenericform'
  defaults:
    _form: '\Drupal\configform\Form\SimpleForm'
    _title: 'Simple Form'
  requirements:
    _permission: 'simple custom form permission'

form.configForm:
  path: '/admin/config/Customconfigform'
  defaults:
    _form: '\Drupal\configform\Form\ConfigForm'
    _title: 'Config Form'
  requirements:
    _permission: 'custom permission'
